### ISSUE TITLE
Chromedriver location

### ISSUE THREAD

**Issue by noraj** [phefley/burp-javascript-security-extension#5]
> Ensure that Chrome/Chromium is installed in a standard location.

```java
java.lang.IllegalStateException: The driver executable does not exist: /usr/lib/chromium-browser/chromedriver
	at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:137)
	at org.openqa.selenium.remote.service.DriverService$Builder.usingDriverExecutable(DriverService.java:272)
	at org.focalpoint.isns.burp.srichecks.DriverServiceManager.startDriverService(DriverServiceManager.java:54)
	at org.focalpoint.isns.burp.srichecks.DriverServiceManager.<init>(DriverServiceManager.java:45)
	at burp.BurpExtender.<init>(BurpExtender.java:58)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at burp.ete.a(Unknown Source)
	at burp.ete.<init>(Unknown Source)
	at burp.dgg.a(Unknown Source)
	at burp.ld.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

The login looks for chromedriver in `/usr/lib/chromium-browser/chromedriver` as if it was the standard way. On ArchLinux and others distro it is located at `/usr/lib/chromium`.

Maybe you should look for several standard path before raising an error.

**Comment by noraj** [comment]
Workaround:

1. `sudo mkdir /usr/lib/chromium-browser`
2. `sudo ln -s /usr/lib/chromium/chromedriver /usr/lib/chromium-browser/chromedriver`

**Comment by noraj** [comment]
There is an option to configure the location in the UI, but the UI won't load on the first place if the driver loading fails...

![image](https://user-images.githubusercontent.com/16578570/68390937-ada84700-0166-11ea-94d8-ebaff533ae0c.png)

**Comment by jakub-botwicz** [comment]
The same problem affects Burp on Windows where creating /usr/lib/chromium-browser directory is not possible.
Please change it so there will be no loading of chromedriver on start, but after selecting the driver.

**Comment by pbielicki** [comment]
I have the same problem on MasOS Monterey (12.x) - I can't write to `/usr/lib` because of the [System Integrity Protection](https://apple.stackexchange.com/questions/208764/cant-write-to-usr-lib)

So, basically this plugin is unusable on MacOS

**Comment by noraj** [comment]
I opened this issue the 7 Nov 2019 but the project has not been updated since 30 Oct 2019 so I guess it is abandoned.
